version: '3.5'

networks:
  laravel:

services:
  #nginx block
  nginx:
    build:
      context: ./docker/nginx
      args:
        DEV_DOMAIN: ${DEV_DOMAIN}
        NGINX_SSL: ${NGINX_SSL}
    image: 'nginx:stable-alpine'
    container_name: ${PROJECT_NAME}-nginx
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    environment:
       VIRTUAL_PORT: 80
       VIRTUAL_HOST: melamart-docker.test
    volumes:
      - ./src:/var/www/html
      - ./docker/socket:/socket
    depends_on:
      - php
      - database
  #mysql block
  database: 
    image: mysql:5.7.22
    container_name: ${PROJECT_NAME}-mysql
    restart: unless-stopped
    tty: true
    ports:
      - 127.0.0.1:3307:3306
    volumes:
      - ./docker/mysql:/var/libs/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
  #php block
  php:
    build:
      context: ./docker/php
      args:
        APP_ENV: ${APP_ENV}
        PHP_VERSION: ${PHP_VERSION}
        REMOTE_WORKING_DIR: ${REMOTE_WORKING_DIR}
    container_name: ${PROJECT_NAME}-php
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./docker/php/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/php/config/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/socket:/socket
    ports:
      - 9000:9000
    depends_on:
      - database

  #composer block
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/var/www/html 
    working_dir: /var/www/html
  #npm block
  npm:
    image: node:13.7
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
  #artisan block
  cwebp:
    image: cmd.cat/cwebp 
    container_name: cwebp
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html

       